import os

KRAKEN_API_KEY = os.getenv("KRAKEN_API_KEY")
KRAKEN_API_SECRET = os.getenv("KRAKEN_API_SECRET")

# Trading pair
PAIR = "BTC/USDT"
# USDT per operation
TRADE_AMOUNT = 10
RSI_PERIOD = 14
RSI_OVERBOUGHT = 70
RSI_OVERSOLD = 30
MACD_SHORT = 12
MACD_LONG = 26
MACD_SIGNAL = 9

LOG_FILE = "logs/trading_bot.log"
