services:
  trading-bot:
    build: .
    container_name: trading_bot
    environment:
      - EXCHANGE=BITGET  # Set to "KRAKEN" or "BITGET"
      - API_KEY=YOUR_API_KEY
      - API_SECRET=YOUR_API_SECRET
      - API_PASSPHRASE=YOUR_API_PASSPHRASE
      - LOG_FILE=/var/logs/trading_bot.log
      - TRADE_HISTORY=/var/logs/trade_history.json
      - PAIR=BTCUSDT # Set to "BTC/USD" for Kraken or BTCUSDT for "BITGET"
      - TRADE_AMOUNT=10
      - TELEGRAM_BOT_TOKEN=YOUR_BOT_TOKEN
      - TELEGRAM_CHAT_ID=CHAT_ID_WITH_BOT
    volumes:
      - ./logs:/var/logs
    restart: unless-stopped
